version: '3'
services:  
  web:
    build: .
    command: ["sh", "-c", "python3 manage.py makemigrations; python3 manage.py migrate; python3 manage.py collectstatic --no-input; gunicorn QuickLander.wsgi:application --bind 0.0.0.0:8001"]
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 8001:8001
volumes:
  static_volume:
  media_volume:
